<?php
/**
 * Wage_TrainEvent extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Wage
 * @package        Wage_TrainEvent
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * trainevent rss feeds block
 * @category    Wage
 * @package     Wage_TrainEvent
 * @author      Ultimate Module Creator
 */
?>

<p class="<?php echo $this->getHtmlClass() ?>">
    <a href="<?php echo $this->escapeHtml(Mage::helper('wage_trainevent/trainevent')->getSignupUrl()) ?>" ><?php echo $this->escapeHtml($this->__($this->getSignupLabel())); ?></a>
</p>
